### ISSUE TITLE
 Failed to find a META6.json file for TinyFloats

### ISSUE THREAD

**Issue by demanuel** [japhb/TinyFloats#1] opened 2021-09-06 09:57 UTC
$ zef install TinyFloats
===> Searching for: TinyFloats
===> Extraction: Failed to find a META6.json file for TinyFloats:ver<0.0.3>:auth<zef:japhb> -- failure is likely
[TinyFloats] Extracting with plugin Zef::Service::Shell::tar+{<anon|1>} aborted.
Type check failed for return value; expected IO::Path but got Any (Any)

**Comment by japhb** [comment] 2021-09-06 17:19
That's really quite strange ... I don't think I've ever seen that error before.  One thing that's a bit odd is that I see the < > around the `ver` but not around the `auth`.

There's clearly a `META6.json` file in the repo ... perhaps a mis-indexing in the fez/zef ecosystem?  Actually, I just ran `zef info TinyFloats` and `zef look TinyFloats` and both show me what I expect to see.

Could have been a temporary failure; could you try that install again?  If it still fails, please post the result of `raku -v` so I can continue to debug; if it succeeds, please let me know and/or close this issue.

**Comment by demanuel** [comment] 2021-09-06 18:06
I tried several times to install it and it always failed.

```
 > zef info TinyFloats
- Info for: TinyFloats
- Identity: TinyFloats:ver<0.0.3>:auth<zef:japhb>
- Recommended By: Zef::Repository::Ecosystems<fez>
- Installed: No
Description:     Convert to/from tiny float formats
License:         Artistic-2.0
Source-url:      https://github.com/japhb/TinyFloats.git
Provides: 1 modules
Depends: 0 items
> zef look TinyFloats
===> Searching for: TinyFloats
===> Extraction: Failed to find a META6.json file for TinyFloats:ver<0.0.3>:auth<zef:japhb> -- failure is likely
[TinyFloats] Extracting with plugin Zef::Service::Shell::tar+{<anon|1>} aborted.
Type check failed for return value; expected IO::Path but got Any (Any)
> zef install TinyFloats
===> Searching for: TinyFloats
===> Extraction: Failed to find a META6.json file for TinyFloats:ver<0.0.3>:auth<zef:japhb> -- failure is likely
[TinyFloats] Extracting with plugin Zef::Service::Shell::tar+{<anon|1>} aborted.
Type check failed for return value; expected IO::Path but got Any (Any)

```

I can install other modules. Example:

```
> zef install Cro::TLS
===> Searching for: Cro::TLS
===> Testing: Cro::TLS:ver<0.8.6>
===> Testing [OK] for Cro::TLS:ver<0.8.6>
===> Installing: Cro::TLS:ver<0.8.6>
> zef install Crypt::Random
===> Searching for: Crypt::Random
===> Testing: Crypt::Random:ver<0.4.1>
===> Testing [OK] for Crypt::Random:ver<0.4.1>
===> Installing: Crypt::Random:ver<0.4.1>
> zef install JSON::JWT
===> Searching for: JSON::JWT
===> Searching for missing dependencies: Digest::HMAC
===> Testing: Digest::HMAC:ver<1.0.2>:auth<github:retupmoca>
===> Testing [OK] for Digest::HMAC:ver<1.0.2>:auth<github:retupmoca>
===> Testing: JSON::JWT:ver<1.0>

```

I also have trouble with another module though:

```
> zef install  CBOR::Simple
===> Searching for: CBOR::Simple
===> Searching for missing dependencies: TinyFloats:ver<0.0.3+>
===> Extraction: Failed to find a META6.json file for CBOR::Simple:ver<0.0.9>:auth<zef:japhb> -- failure is likely
[CBOR::Simple] Extracting with plugin Zef::Service::Shell::tar+{<anon|1>} aborted.
===> Extraction: Failed to find a META6.json file for TinyFloats:ver<0.0.3>:auth<zef:japhb> -- failure is likely
[TinyFloats] Extracting with plugin Zef::Service::Shell::tar+{<anon|1>} aborted.
Type check failed for return value; expected IO::Path but got Any (Any)
```

Zef version:

```
> zef --version
v0.11.11
```

rakudo version:
```
> raku --version
Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2021.08.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
Built on MoarVM version 2021.08.

```

**Comment by demanuel** [comment] 2021-09-06 18:13
It works when doing a local install:

```
> git clone https://github.com/japhb/TinyFloats.git
Cloning into 'TinyFloats'...
remote: Enumerating objects: 82, done.
remote: Counting objects: 100% (82/82), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 82 (delta 35), reused 74 (delta 27), pack-reused 0
Receiving objects: 100% (82/82), 13.53 KiB | 338.00 KiB/s, done.
Resolving deltas: 100% (35/35), done.
> zef install ./TinyFloats/
===> Testing: TinyFloats:ver<0.0.3>:auth<zef:japhb>
===> Testing [OK] for TinyFloats:ver<0.0.3>:auth<zef:japhb>
===> Installing: TinyFloats:ver<0.0.3>:auth<zef:japhb>
```

**Comment by japhb** [comment] 2021-09-06 18:27
We have the same `zef` version, and we're pretty close on Rakudo versions (I run a dev commit, but otherwise not far apart).  Your `zef info` appears reasonable, but clearly if `zef look` fails for you, and `git clone`/`zef install $dir` works, it's the extraction that's failing in some way, not the install itself (as hinted by the error message, I suppose).

Of the things you've tested, I see working modules from the `p6c` and `cpan` ecosystems, but only failures from the `fez` ecosystem, though it appears you only tested other modules of mine in that case.

Could you try `zef update` followed by `zef install` of a module that is in the `fez` ecosystem, but is *not* one of mine, so I can determine whether the problem is ecosystem-related or something weird with my packaging?

**Comment by demanuel** [comment] 2021-09-06 18:41
You are right. It seems to be an issue with the packages available from fez ecosystem:

```
 zef install ACME::Fez
===> Searching for: ACME::Fez
===> Extraction: Failed to find a META6.json file for ACME::Fez:ver<1>:auth<zef:tony-o>:api<0> -- failure is likely
[ACME::Fez] Extracting with plugin Zef::Service::Shell::tar+{<anon|1>} aborted.
Type check failed for return value; expected IO::Path but got Any (Any)
```

**Comment by demanuel** [comment] 2021-09-06 18:42
I will open an issue with zef.

Please close it if you agree :-)

**Comment by japhb** [comment] 2021-09-06 18:43
Thanks @demanuel, closing!

**Closed as completed by japhb** 2021-09-06 18:43 UTC
